version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Changeme@12"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    expose:
      - "1433"
    volumes:
      - dbdata:/var/opt/mssql/data

  api:
    container_name: smartsystems-identity-server-api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./src/
    command: uvicorn main:api --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    expose:
      - "8001"
    depends_on:
      - db

volumes:
  dbdata:
