version: '3.8'

networks:
  smartsystems_vn:
    driver: bridge

services:
  api:
    container_name: smartsystems-identity-server-api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./src/
      platforms:
        - linux/arm64
    ports:
      - "8001:80"
    # depends_on:
    #   - mssql
    networks:
      - smartsystems_vn
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-dev} 
    command: uvicorn main:api --host 0.0.0.0 --port 80 --reload

  # mssql:
  #   image: mcr.microsoft.com/azure-sql-edge:latest
  #   ports:
  #     - 1433:1433
  #   environment:
  #     - ACCEPT_EULA=1
  #     - SA_PASSWORD=Passw@rd
  #   volumes:
  #     - ./SQLDB:/var/opt/mssql/DDL
  #   networks:
  #     - smartsystems_vn
  #   command:
  #     - /bin/bash
  #     - -c 
  #     - |
  #       # Launch MSSQL and send to background
  #       /opt/mssql/bin/sqlservr &
  #       # Wait 30 seconds for it to be available
  #       sleep 60
  #       /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Passw@rd -i /var/opt/mssql/DDL/IdentitySQL_init.sql
  #       /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Passw@rd -i /var/opt/mssql/DDL/IdentityTables_init.sql
  #       /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Passw@rd -i /var/opt/mssql/DDL/TestData_init.sql
  #       # So that the container doesn't shut down, sleep this thread
  #       sleep infinity

