export const env = {
    API_URL: process.env.REACT_APP_API_URL,
    PLANNER_REPORT: process.env.REACT_APP_POWERBI_REPORT_PLANNER,
    PPPR_REPORT: process.env.REACT_APP_POWERBI_REPORT_PPPR,
    SRES_GRAPH: process.env.REACT_APP_POWERBI_GRAPH_SRES,
    CLIENT_ID: process.env.REACT_APP_MSAL_CLIENT_ID,
    TENANT_ID: process.env.REACT_APP_MSAL_TENANT_ID,
    REDIRECT_URI: process.env.REACT_APP_MSAL_REDIRECT_URI,
    USER_IMPERSONATION: process.env.REACT_APP_MSAL_USER_IMPERSONATION,
    INSIGHTS_INSTRUMENTATIONKEY: process.env.REACT_APP_APPINSIGHTS_INSTRUMENTATIONKEY,
    APP_TIMEZONE: "Europe/London",
    APP_ENV: process.env.REACT_APP_ENV,
}